toggle_hud=Shift_R+F12
font_scale=2
fps
fps_metrics=avg
fps_metrics=avg,0.01
frametime
gpu_stats
gpu_temp
cpu_stats
cpu_temp
ram
vram
fsr
display_server
present_mode
fps_limit=120
fps_limit_method=early
winesync
